swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /recipe:
    get:
      operationId: "recipe.read_all"
      tags:
        - Recipe
      description: "Read all recipe"
      responses:
        200:
          description: "Successful read recipe list operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                name:
                  type: "string"
  /recipeItem:
    get:
      operationId: recipeItem.read_all
      tags:
        - RecipeItem
      description: "Read all RecipeItem"
      parameters:
        - name: recipeId
          in: query
          description: id of the recipe
          type: integer
          required: False
      responses:
        200:
          description: "Successful read RecipeItem list operation"
          schema:
            type: "array"
            items:
              properties:
                ingredient:
                  type: "integer"
                recipe:
                  type: "integer"
                ml:
                  type: number
  /ingredient:
    get:
      operationId: "ingredient.read_all"
      tags:
        - Ingredient
      description: "Read all ingredient"
      responses:
        200:
          description: "Successful read ingredient list operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                name:
                  type: "string"
    put:
      operationId: "ingredient.insert"
      tags:
        - Ingredient
      description: "insert a ingredient"
      parameters:
        - in: body
          name: ingredient
          description: The ingredient to insert.
          schema:
            properties:
              name:
                type: "string"
      responses:
        200:
          description: "Successful insert ingredient operation"
          schema:
            properties:
              id:
                type: "integer"
              name:
                type: "string"